change-template: "- #$NUMBER - $TITLE (@$AUTHOR)"
categories:
  - title: "⚠ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🤖 Automated Updates"
    collapse-after: 1
    labels:
      - "ci-generated"
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## What’s Changed

  $CHANGES
