"""Test the unknown value fallback for enums fed by device-reported data."""

from __future__ import annotations

import logging

import pytest

from zwave_js_server.const import CommandClass, UnknownValueIntEnum
from zwave_js_server.const.command_class.battery import BatteryReplacementStatus
from zwave_js_server.const.command_class.multilevel_switch import (
    MultilevelSwitchCommand,
)
from zwave_js_server.const.command_class.notification import NotificationType
from zwave_js_server.const.command_class.power_level import PowerLevelTestStatus

# Each test uses a distinct out-of-range value. Unknown members are cached on
# first lookup, so sharing a value between tests would make the ones asserting
# on log output depend on execution order.


def test_unknown_value_preserves_raw_value() -> None:
    """Test an unknown value yields a member carrying the raw value.

    Regression test for home-assistant/core#184144, where a Powerlevel CC report
    with status 190 raised ValueError out of the listen loop.
    """
    status = PowerLevelTestStatus(190)

    assert status.value == 190
    assert status == 190
    assert status.name == "UNKNOWN_190"
    assert status.is_unknown is True


def test_known_value_is_the_real_member() -> None:
    """Test known values still resolve to the canonical member."""
    status = PowerLevelTestStatus(0)

    assert status is PowerLevelTestStatus.FAILED
    assert status.name == "FAILED"
    assert status.is_unknown is False


def test_unknown_member_is_not_registered() -> None:
    """Test an unknown value does not become part of the enum's membership."""
    PowerLevelTestStatus(191)

    assert "UNKNOWN_191" not in PowerLevelTestStatus.__members__
    assert 191 not in [member.value for member in PowerLevelTestStatus]


def test_unknown_value_logs_a_warning(caplog: pytest.LogCaptureFixture) -> None:
    """Test an unknown value is reported so it can be diagnosed."""
    with caplog.at_level(logging.WARNING):
        PowerLevelTestStatus(192)

    assert "PowerLevelTestStatus" in caplog.text
    assert "192" in caplog.text


def test_unknown_value_is_cached(caplog: pytest.LogCaptureFixture) -> None:
    """Test a repeated unknown value reuses the member and warns only once."""
    with caplog.at_level(logging.WARNING):
        first = PowerLevelTestStatus(193)
        second = PowerLevelTestStatus(193)

    assert first is second
    assert caplog.text.count("193") == 1


def test_non_int_value_still_raises() -> None:
    """Test a value that is not an int remains an error."""
    with pytest.raises(ValueError):
        PowerLevelTestStatus("not-a-status")


@pytest.mark.parametrize(
    "enum",
    [
        BatteryReplacementStatus,
        CommandClass,
        MultilevelSwitchCommand,
        PowerLevelTestStatus,
    ],
)
def test_device_reported_enums_tolerate_unknown_values(
    enum: type[UnknownValueIntEnum],
) -> None:
    """Test every device-reported enum tolerates an out-of-range value."""
    assert issubclass(enum, UnknownValueIntEnum)
    assert enum(190).value == 190


def test_generated_notification_enum_preserves_value() -> None:
    """Test the autogenerated notification enums also keep the raw value."""
    notification_type = NotificationType(200)

    assert notification_type.value == 200
    assert notification_type.is_unknown is True


def test_generated_unknown_sentinel_is_removed() -> None:
    """Test the old UNKNOWN sentinel is gone, so stale checks fail loudly.

    Unknown values now carry their own value, so `== NotificationType.UNKNOWN`
    would silently take the wrong branch. Removing the member turns that into an
    AttributeError at the comparison site, which consumers cannot miss.
    """
    assert "UNKNOWN" not in NotificationType.__members__
    with pytest.raises(AttributeError):
        _ = NotificationType.UNKNOWN
