"""Constants for the Notification CC."""

# ----------------------------------------------------------------------------------- #
# **BEGINNING OF AUTOGENERATED CONTENT** (TO ADD ADDITIONAL MANUAL CONTENT, LOOK FOR  #
# THE "END OF AUTOGENERATED CONTENT" COMMENT BLOCK AND ADD YOUR CODE BELOW IT)        #
# ----------------------------------------------------------------------------------- #

from __future__ import annotations

from enum import IntEnum

CC_SPECIFIC_NOTIFICATION_TYPE = "notificationType"


class NotificationType(IntEnum):
    """Enum for known notification types."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ACCESS_CONTROL = 6
    APPLIANCE = 12
    CLOCK = 11
    CO_ALARM = 2
    CO2_ALARM = 3
    GAS_ALARM = 18
    HEAT_ALARM = 4
    HOME_HEALTH = 13
    HOME_MONITORING = 22
    HOME_SECURITY = 7
    IRRIGATION = 17
    LIGHT_SENSOR = 20
    PEST_CONTROL = 19
    POWER_MANAGEMENT = 8
    SIREN = 14
    SMOKE_ALARM = 1
    SYSTEM = 10
    WATER_ALARM = 5
    WATER_QUALITY_MONITORING = 21
    WATER_VALVE = 15
    WEATHER_ALARM = 16


class NotificationEvent(IntEnum):
    """Common base class for Notification CC states enums."""


class AccessControlLockStateNotificationEvent(NotificationEvent):
    """Enum for known access control lock state notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_JAMMED = 11
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlLockStateNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlLockStateNotificationEvent.UNKNOWN


class AccessControlKeypadStateNotificationEvent(NotificationEvent):
    """Enum for known access control keypad state notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_BUSY = 17
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_TEMPORARY_DISABLED = 16
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlKeypadStateNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlKeypadStateNotificationEvent.UNKNOWN


class AccessControlDoorStateNotificationEvent(NotificationEvent):
    """Enum for known access control door state notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34
    WINDOW_DOOR_IS_CLOSED = 23
    WINDOW_DOOR_IS_OPEN = 22

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlDoorStateNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlDoorStateNotificationEvent.UNKNOWN


class AccessControlDoorHandleStateNotificationEvent(NotificationEvent):
    """Enum for known access control door handle state notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34
    WINDOW_DOOR_HANDLE_IS_CLOSED = 25
    WINDOW_DOOR_HANDLE_IS_OPEN = 24

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlDoorHandleStateNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlDoorHandleStateNotificationEvent.UNKNOWN


class AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known access control barrier performing initialization process status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_PERFORMING_INITIALIZATION_PROCESS = 64
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return (
            AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent.UNKNOWN
        )


class AccessControlBarrierUlDisablingStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier ul disabling status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    BARRIER_UNATTENDED_OPERATION_HAS_BEEN_DISABLED_PER_UL_REQUIREMENTS = 69
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierUlDisablingStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierUlDisablingStatusNotificationEvent.UNKNOWN


class AccessControlBarrierVacationModeStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier vacation mode status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    BARRIER_VACATION_MODE = 71
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierVacationModeStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierVacationModeStatusNotificationEvent.UNKNOWN


class AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier safety beam obstacle status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SAFETY_BEAM_OBSTACLE = 72
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent.UNKNOWN


class AccessControlBarrierSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SENSOR_NOT_DETECTED_SUPERVISORY_ERROR = 73
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierSensorStatusNotificationEvent.UNKNOWN


class AccessControlBarrierBatteryStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier battery status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SENSOR_LOW_BATTERY_WARNING = 74
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierBatteryStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierBatteryStatusNotificationEvent.UNKNOWN


class AccessControlBarrierShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier short-circuit status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_DETECTED_SHORT_IN_WALL_STATION_WIRES = 75
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierShortCircuitStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierShortCircuitStatusNotificationEvent.UNKNOWN


class AccessControlBarrierControlStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier control status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_ASSOCIATED_WITH_NON_Z_WAVE_REMOTE_CONTROL = 76
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> AccessControlBarrierControlStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return AccessControlBarrierControlStatusNotificationEvent.UNKNOWN


class ApplianceProgramStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance program status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    PROGRAM_COMPLETED = 3
    PROGRAM_IN_PROGRESS = 2
    PROGRAM_STARTED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceProgramStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceProgramStatusNotificationEvent.UNKNOWN


class ApplianceMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACE_MAIN_FILTER = 4

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceMaintenanceStatusNotificationEvent.UNKNOWN


class ApplianceApplianceStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance appliance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BOILING = 8
    DRAINING = 14
    DRYING = 18
    RINSING = 12
    SPINNING = 16
    SUPPLYING_WATER = 6
    WASHING = 10

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceApplianceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceApplianceStatusNotificationEvent.UNKNOWN


class ApplianceTargetTemperatureFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance target temperature failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FAILURE_TO_SET_TARGET_TEMPERATURE = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceTargetTemperatureFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceTargetTemperatureFailureStatusNotificationEvent.UNKNOWN


class ApplianceWaterSupplyFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance water supply failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_SUPPLY_FAILURE = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceWaterSupplyFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceWaterSupplyFailureStatusNotificationEvent.UNKNOWN


class ApplianceBoilingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance boiling failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BOILING_FAILURE = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceBoilingFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceBoilingFailureStatusNotificationEvent.UNKNOWN


class ApplianceWashingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance washing failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WASHING_FAILURE = 11

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceWashingFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceWashingFailureStatusNotificationEvent.UNKNOWN


class ApplianceRinsingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance rinsing failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    RINSING_FAILURE = 13

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceRinsingFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceRinsingFailureStatusNotificationEvent.UNKNOWN


class ApplianceDrainingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance draining failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    DRAINING_FAILURE = 15

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceDrainingFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceDrainingFailureStatusNotificationEvent.UNKNOWN


class ApplianceSpinningFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance spinning failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    SPINNING_FAILURE = 17

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceSpinningFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceSpinningFailureStatusNotificationEvent.UNKNOWN


class ApplianceDryingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance drying failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    DRYING_FAILURE = 19

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceDryingFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceDryingFailureStatusNotificationEvent.UNKNOWN


class ApplianceFanFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance fan failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FAN_FAILURE = 20

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceFanFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceFanFailureStatusNotificationEvent.UNKNOWN


class ApplianceCompressorFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance compressor failure status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    COMPRESSOR_FAILURE = 21

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> ApplianceCompressorFailureStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return ApplianceCompressorFailureStatusNotificationEvent.UNKNOWN


class CoAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CARBON_MONOXIDE_DETECTED = 2
    CARBON_MONOXIDE_DETECTED_LOCATION_PROVIDED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> CoAlarmSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return CoAlarmSensorStatusNotificationEvent.UNKNOWN


class CoAlarmTestStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm test status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CARBON_MONOXIDE_TEST = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> CoAlarmTestStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return CoAlarmTestStatusNotificationEvent.UNKNOWN


class CoAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> CoAlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return CoAlarmMaintenanceStatusNotificationEvent.UNKNOWN


class CoAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALARM_SILENCED = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> CoAlarmAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return CoAlarmAlarmStatusNotificationEvent.UNKNOWN


class CoAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm periodic inspection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> CoAlarmPeriodicInspectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return CoAlarmPeriodicInspectionStatusNotificationEvent.UNKNOWN


class Co2AlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CARBON_DIOXIDE_DETECTED = 2
    CARBON_DIOXIDE_DETECTED_LOCATION_PROVIDED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> Co2AlarmSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return Co2AlarmSensorStatusNotificationEvent.UNKNOWN


class Co2AlarmTestStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm test status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CARBON_DIOXIDE_TEST = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> Co2AlarmTestStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return Co2AlarmTestStatusNotificationEvent.UNKNOWN


class Co2AlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> Co2AlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return Co2AlarmMaintenanceStatusNotificationEvent.UNKNOWN


class Co2AlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALARM_SILENCED = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> Co2AlarmAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return Co2AlarmAlarmStatusNotificationEvent.UNKNOWN


class Co2AlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm periodic inspection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> Co2AlarmPeriodicInspectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return Co2AlarmPeriodicInspectionStatusNotificationEvent.UNKNOWN


class GasAlarmCombustibleGasStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm combustible gas status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    COMBUSTIBLE_GAS_DETECTED = 2
    COMBUSTIBLE_GAS_DETECTED_LOCATION_PROVIDED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> GasAlarmCombustibleGasStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return GasAlarmCombustibleGasStatusNotificationEvent.UNKNOWN


class GasAlarmToxicGasStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm toxic gas status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    TOXIC_GAS_DETECTED = 4
    TOXIC_GAS_DETECTED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> GasAlarmToxicGasStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return GasAlarmToxicGasStatusNotificationEvent.UNKNOWN


class GasAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    GAS_ALARM_TEST = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> GasAlarmAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return GasAlarmAlarmStatusNotificationEvent.UNKNOWN


class GasAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACEMENT_REQUIRED = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> GasAlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return GasAlarmMaintenanceStatusNotificationEvent.UNKNOWN


class HeatAlarmHeatSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm heat sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    OVERHEAT_DETECTED = 2
    OVERHEAT_DETECTED_LOCATION_PROVIDED = 1
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3
    UNDERHEAT_DETECTED = 6
    UNDERHEAT_DETECTED_LOCATION_PROVIDED = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HeatAlarmHeatSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HeatAlarmHeatSensorStatusNotificationEvent.UNKNOWN


class HeatAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALARM_SILENCED = 9
    HEAT_ALARM_TEST = 7
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HeatAlarmAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HeatAlarmAlarmStatusNotificationEvent.UNKNOWN


class HeatAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3
    REPLACEMENT_REQUIRED_END_OF_LIFE = 8

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HeatAlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HeatAlarmMaintenanceStatusNotificationEvent.UNKNOWN


class HeatAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm periodic inspection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 11
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HeatAlarmPeriodicInspectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HeatAlarmPeriodicInspectionStatusNotificationEvent.UNKNOWN


class HeatAlarmDustInDeviceStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm dust in device status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_DUST_IN_DEVICE = 10
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HeatAlarmDustInDeviceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HeatAlarmDustInDeviceStatusNotificationEvent.UNKNOWN


class HomeHealthPositionStatusNotificationEvent(NotificationEvent):
    """Enum for known home health position status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FALL_DETECTED = 12
    LEAVING_BED = 1
    LYING_ON_BED = 3
    POSTURE_CHANGED = 4
    SITTING_ON_BED = 2
    SITTING_ON_BED_EDGE = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeHealthPositionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeHealthPositionStatusNotificationEvent.UNKNOWN


class HomeHealthVocLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known home health voc level status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    VOLATILE_ORGANIC_COMPOUND_LEVEL = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeHealthVocLevelStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeHealthVocLevelStatusNotificationEvent.UNKNOWN


class HomeHealthSleepApneaStatusNotificationEvent(NotificationEvent):
    """Enum for known home health sleep apnea status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    SLEEP_APNEA_DETECTED = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeHealthSleepApneaStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeHealthSleepApneaStatusNotificationEvent.UNKNOWN


class HomeHealthSleepStageStatusNotificationEvent(NotificationEvent):
    """Enum for known home health sleep stage status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    SLEEP_STAGE_0_DETECTED_DREAMING_REM = 8
    SLEEP_STAGE_1_DETECTED_LIGHT_SLEEP_NON_REM_1 = 9
    SLEEP_STAGE_2_DETECTED_MEDIUM_SLEEP_NON_REM_2 = 10
    SLEEP_STAGE_3_DETECTED_DEEP_SLEEP_NON_REM_3 = 11

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeHealthSleepStageStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeHealthSleepStageStatusNotificationEvent.UNKNOWN


class HomeMonitoringHomeOccupancyStatusNotificationEvent(NotificationEvent):
    """Enum for known home monitoring home occupancy status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    HOME_OCCUPIED = 2
    HOME_OCCUPIED_LOCATION_PROVIDED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeMonitoringHomeOccupancyStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeMonitoringHomeOccupancyStatusNotificationEvent.UNKNOWN


class HomeSecuritySensorStatusNotificationEvent(NotificationEvent):
    """Enum for known home security sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    INTRUSION = 2
    INTRUSION_LOCATION_PROVIDED = 1
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeSecuritySensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeSecuritySensorStatusNotificationEvent.UNKNOWN


class HomeSecurityCoverStatusNotificationEvent(NotificationEvent):
    """Enum for known home security cover status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_COVER_REMOVED = 3
    TAMPERING_PRODUCT_MOVED = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeSecurityCoverStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeSecurityCoverStatusNotificationEvent.UNKNOWN


class HomeSecurityMotionSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known home security motion sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    MOTION_DETECTION = 8
    MOTION_DETECTION_LOCATION_PROVIDED = 7
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeSecurityMotionSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeSecurityMotionSensorStatusNotificationEvent.UNKNOWN


class HomeSecurityMagneticInterferenceStatusNotificationEvent(NotificationEvent):
    """Enum for known home security magnetic interference status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    MAGNETIC_FIELD_INTERFERENCE_DETECTED = 11
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> HomeSecurityMagneticInterferenceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return HomeSecurityMagneticInterferenceStatusNotificationEvent.UNKNOWN


class IrrigationScheduleStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation schedule (id) status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    SCHEDULE_FINISHED = 2
    SCHEDULE_STARTED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> IrrigationScheduleStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return IrrigationScheduleStatusNotificationEvent.UNKNOWN


class IrrigationValveRunStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation valve (id) run status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    VALVE_TABLE_RUN_FINISHED = 4
    VALVE_TABLE_RUN_STARTED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> IrrigationValveRunStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return IrrigationValveRunStatusNotificationEvent.UNKNOWN


class IrrigationDeviceConfigurationStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation device configuration status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    DEVICE_IS_NOT_CONFIGURED = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> IrrigationDeviceConfigurationStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return IrrigationDeviceConfigurationStatusNotificationEvent.UNKNOWN


class LightSensorLightDetectionStatusNotificationEvent(NotificationEvent):
    """Enum for known light sensor light detection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    LIGHT_COLOR_TRANSITION_DETECTED = 2
    LIGHT_DETECTED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> LightSensorLightDetectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return LightSensorLightDetectionStatusNotificationEvent.UNKNOWN


class PestControlTrapStatusNotificationEvent(NotificationEvent):
    """Enum for known pest control trap status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    PEST_DETECTED = 6
    PEST_DETECTED_LOCATION_PROVIDED = 5
    PEST_EXTERMINATED = 8
    PEST_EXTERMINATED_LOCATION_PROVIDED = 7
    TRAP_ARMED = 2
    TRAP_ARMED_LOCATION_PROVIDED = 1
    TRAP_RE_ARM_REQUIRED = 4
    TRAP_RE_ARM_REQUIRED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PestControlTrapStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PestControlTrapStatusNotificationEvent.UNKNOWN


class PowerManagementPowerStatusNotificationEvent(NotificationEvent):
    """Enum for known power management power status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    POWER_HAS_BEEN_APPLIED = 1
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementPowerStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementPowerStatusNotificationEvent.UNKNOWN


class PowerManagementMainsStatusNotificationEvent(NotificationEvent):
    """Enum for known power management mains status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    AC_MAINS_DISCONNECTED = 2
    AC_MAINS_RE_CONNECTED = 3
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementMainsStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementMainsStatusNotificationEvent.UNKNOWN


class PowerManagementOverCurrentStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-current status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    OVER_CURRENT_DETECTED = 6
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementOverCurrentStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementOverCurrentStatusNotificationEvent.UNKNOWN


class PowerManagementOverVoltageStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-voltage status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    OVER_VOLTAGE_DETECTED = 7
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementOverVoltageStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementOverVoltageStatusNotificationEvent.UNKNOWN


class PowerManagementOverLoadStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-load status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    OVER_LOAD_DETECTED = 8
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementOverLoadStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementOverLoadStatusNotificationEvent.UNKNOWN


class PowerManagementLoadErrorStatusNotificationEvent(NotificationEvent):
    """Enum for known power management load error status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    LOAD_ERROR = 9
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementLoadErrorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementLoadErrorStatusNotificationEvent.UNKNOWN


class PowerManagementBatteryMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BATTERY_FLUID_IS_LOW = 17
    REPLACE_BATTERY_NOW = 11
    REPLACE_BATTERY_SOON = 10
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementBatteryMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementBatteryMaintenanceStatusNotificationEvent.UNKNOWN


class PowerManagementBatteryLoadStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery load status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BATTERY_IS_CHARGING = 12
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementBatteryLoadStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementBatteryLoadStatusNotificationEvent.UNKNOWN


class PowerManagementBatteryLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery level status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BATTERY_IS_FULLY_CHARGED = 13
    CHARGE_BATTERY_NOW = 15
    CHARGE_BATTERY_SOON = 14
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementBatteryLevelStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementBatteryLevelStatusNotificationEvent.UNKNOWN


class PowerManagementBackupBatteryLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known power management backup battery level status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    BACK_UP_BATTERY_DISCONNECTED = 18
    BACK_UP_BATTERY_IS_LOW = 16
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> PowerManagementBackupBatteryLevelStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return PowerManagementBackupBatteryLevelStatusNotificationEvent.UNKNOWN


class SirenSirenStatusNotificationEvent(NotificationEvent):
    """Enum for known siren siren status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    SIREN_ACTIVE = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SirenSirenStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SirenSirenStatusNotificationEvent.UNKNOWN


class SmokeAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    SMOKE_DETECTED = 2
    SMOKE_DETECTED_LOCATION_PROVIDED = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SmokeAlarmSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SmokeAlarmSensorStatusNotificationEvent.UNKNOWN


class SmokeAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ALARM_SILENCED = 6
    SMOKE_ALARM_TEST = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SmokeAlarmAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SmokeAlarmAlarmStatusNotificationEvent.UNKNOWN


class SmokeAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SmokeAlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SmokeAlarmMaintenanceStatusNotificationEvent.UNKNOWN


class SmokeAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm periodic inspection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SmokeAlarmPeriodicInspectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SmokeAlarmPeriodicInspectionStatusNotificationEvent.UNKNOWN


class SmokeAlarmDustInDeviceStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm dust in device status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MAINTENANCE_REQUIRED_DUST_IN_DEVICE = 8

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> SmokeAlarmDustInDeviceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return SmokeAlarmDustInDeviceStatusNotificationEvent.UNKNOWN


class WaterAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_LEAK_DETECTED = 2
    WATER_LEAK_DETECTED_LOCATION_PROVIDED = 1
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmSensorStatusNotificationEvent.UNKNOWN


class WaterAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm maintenance status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    REPLACE_WATER_FILTER = 5
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmMaintenanceStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmMaintenanceStatusNotificationEvent.UNKNOWN


class WaterAlarmWaterFlowAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water flow alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_FLOW_ALARM = 6
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmWaterFlowAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmWaterFlowAlarmStatusNotificationEvent.UNKNOWN


class WaterAlarmWaterPressureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water pressure alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3
    WATER_PRESSURE_ALARM = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmWaterPressureAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmWaterPressureAlarmStatusNotificationEvent.UNKNOWN


class WaterAlarmWaterTemperatureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water temperature alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3
    WATER_TEMPERATURE_ALARM = 8

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmWaterTemperatureAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmWaterTemperatureAlarmStatusNotificationEvent.UNKNOWN


class WaterAlarmWaterLevelAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water level alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_LEVEL_ALARM = 9
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmWaterLevelAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmWaterLevelAlarmStatusNotificationEvent.UNKNOWN


class WaterAlarmPumpStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm pump status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    SUMP_PUMP_ACTIVE = 10
    SUMP_PUMP_FAILURE = 11
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterAlarmPumpStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterAlarmPumpStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringChlorineAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring chlorine alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CHLORINE_ALARM = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringChlorineAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringChlorineAlarmStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringAcidityStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring acidity (ph) status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ACIDITY_PH_ALARM = 2

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringAcidityStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringAcidityStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring water oxidation alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_OXIDATION_ALARM = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringChlorineSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring chlorine sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    CHLORINE_EMPTY = 4

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringChlorineSensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringChlorineSensorStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringAciditySensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring acidity (ph) sensor status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    ACIDITY_PH_EMPTY = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringAciditySensorStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringAciditySensorStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring waterflow measuring station sensor notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATERFLOW_MEASURING_STATION_SHORTAGE_DETECTED = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return (
            WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent.UNKNOWN
        )


class WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring waterflow clear water sensor notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATERFLOW_CLEAR_WATER_SHORTAGE_DETECTED = 7

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent.UNKNOWN


class WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring disinfection system status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    DISINFECTION_SYSTEM_ERROR_DETECTED = 8

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringFilterCleaningStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring filter cleaning status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FILTER_CLEANING_ONGOING = 9

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringFilterCleaningStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringFilterCleaningStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringHeatingStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring heating status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    HEATING_OPERATION_ONGOING = 10

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringHeatingStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringHeatingStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringFilterPumpStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring filter pump status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FILTER_PUMP_OPERATION_ONGOING = 11

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringFilterPumpStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringFilterPumpStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring freshwater flow status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FRESHWATER_OPERATION_ONGOING = 12

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringDryProtectionStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring dry protection status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    DRY_PROTECTION_OPERATION_ACTIVE = 13

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringDryProtectionStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringDryProtectionStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringWaterTankStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring water tank status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    WATER_TANK_IS_EMPTY = 14
    WATER_TANK_IS_FULL = 16
    WATER_TANK_LEVEL_IS_UNKNOWN = 15

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterQualityMonitoringWaterTankStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringWaterTankStatusNotificationEvent.UNKNOWN


class WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring collective disorder status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    COLLECTIVE_DISORDER = 17

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> (
        WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent
    ):  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent.UNKNOWN


class WaterValveValveOperationStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve operation status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    VALVE_OPERATION = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveValveOperationStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveValveOperationStatusNotificationEvent.UNKNOWN


class WaterValveMasterValveOperationStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve operation status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MASTER_VALVE_OPERATION = 2

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveMasterValveOperationStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveMasterValveOperationStatusNotificationEvent.UNKNOWN


class WaterValveValveShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve short circuit status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    VALVE_SHORT_CIRCUIT = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveValveShortCircuitStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveValveShortCircuitStatusNotificationEvent.UNKNOWN


class WaterValveMasterValveShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve short circuit status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MASTER_VALVE_SHORT_CIRCUIT = 4

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveMasterValveShortCircuitStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveMasterValveShortCircuitStatusNotificationEvent.UNKNOWN


class WaterValveValveCurrentAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve current alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    VALVE_CURRENT_ALARM = 5

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveValveCurrentAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveValveCurrentAlarmStatusNotificationEvent.UNKNOWN


class WaterValveMasterValveCurrentAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve current alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MASTER_VALVE_CURRENT_ALARM = 6

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WaterValveMasterValveCurrentAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WaterValveMasterValveCurrentAlarmStatusNotificationEvent.UNKNOWN


class WeatherAlarmRainAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm rain alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    RAIN_ALARM = 1

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WeatherAlarmRainAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WeatherAlarmRainAlarmStatusNotificationEvent.UNKNOWN


class WeatherAlarmMoistureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm moisture alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    MOISTURE_ALARM = 2

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WeatherAlarmMoistureAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WeatherAlarmMoistureAlarmStatusNotificationEvent.UNKNOWN


class WeatherAlarmFreezeAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm freeze alarm status notification event."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    UNKNOWN = -1
    FREEZE_ALARM = 3

    @classmethod
    def _missing_(
        cls: type, value: object
    ) -> WeatherAlarmFreezeAlarmStatusNotificationEvent:  # noqa: ARG003
        """Set default enum member if an unknown value is provided."""
        return WeatherAlarmFreezeAlarmStatusNotificationEvent.UNKNOWN


NOTIFICATION_TYPE_TO_EVENT_MAP: dict[NotificationType, set[type[NotificationEvent]]] = {
    NotificationType.ACCESS_CONTROL: {
        AccessControlBarrierBatteryStatusNotificationEvent,
        AccessControlBarrierControlStatusNotificationEvent,
        AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent,
        AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent,
        AccessControlBarrierSensorStatusNotificationEvent,
        AccessControlBarrierShortCircuitStatusNotificationEvent,
        AccessControlBarrierUlDisablingStatusNotificationEvent,
        AccessControlBarrierVacationModeStatusNotificationEvent,
        AccessControlDoorHandleStateNotificationEvent,
        AccessControlDoorStateNotificationEvent,
        AccessControlKeypadStateNotificationEvent,
        AccessControlLockStateNotificationEvent,
    },
    NotificationType.APPLIANCE: {
        ApplianceApplianceStatusNotificationEvent,
        ApplianceBoilingFailureStatusNotificationEvent,
        ApplianceCompressorFailureStatusNotificationEvent,
        ApplianceDrainingFailureStatusNotificationEvent,
        ApplianceDryingFailureStatusNotificationEvent,
        ApplianceFanFailureStatusNotificationEvent,
        ApplianceMaintenanceStatusNotificationEvent,
        ApplianceProgramStatusNotificationEvent,
        ApplianceRinsingFailureStatusNotificationEvent,
        ApplianceSpinningFailureStatusNotificationEvent,
        ApplianceTargetTemperatureFailureStatusNotificationEvent,
        ApplianceWashingFailureStatusNotificationEvent,
        ApplianceWaterSupplyFailureStatusNotificationEvent,
    },
    NotificationType.CO_ALARM: {
        CoAlarmAlarmStatusNotificationEvent,
        CoAlarmMaintenanceStatusNotificationEvent,
        CoAlarmPeriodicInspectionStatusNotificationEvent,
        CoAlarmSensorStatusNotificationEvent,
        CoAlarmTestStatusNotificationEvent,
    },
    NotificationType.CO2_ALARM: {
        Co2AlarmAlarmStatusNotificationEvent,
        Co2AlarmMaintenanceStatusNotificationEvent,
        Co2AlarmPeriodicInspectionStatusNotificationEvent,
        Co2AlarmSensorStatusNotificationEvent,
        Co2AlarmTestStatusNotificationEvent,
    },
    NotificationType.GAS_ALARM: {
        GasAlarmAlarmStatusNotificationEvent,
        GasAlarmCombustibleGasStatusNotificationEvent,
        GasAlarmMaintenanceStatusNotificationEvent,
        GasAlarmToxicGasStatusNotificationEvent,
    },
    NotificationType.HEAT_ALARM: {
        HeatAlarmAlarmStatusNotificationEvent,
        HeatAlarmDustInDeviceStatusNotificationEvent,
        HeatAlarmHeatSensorStatusNotificationEvent,
        HeatAlarmMaintenanceStatusNotificationEvent,
        HeatAlarmPeriodicInspectionStatusNotificationEvent,
    },
    NotificationType.HOME_HEALTH: {
        HomeHealthPositionStatusNotificationEvent,
        HomeHealthSleepApneaStatusNotificationEvent,
        HomeHealthSleepStageStatusNotificationEvent,
        HomeHealthVocLevelStatusNotificationEvent,
    },
    NotificationType.HOME_MONITORING: {
        HomeMonitoringHomeOccupancyStatusNotificationEvent,
    },
    NotificationType.HOME_SECURITY: {
        HomeSecurityCoverStatusNotificationEvent,
        HomeSecurityMagneticInterferenceStatusNotificationEvent,
        HomeSecurityMotionSensorStatusNotificationEvent,
        HomeSecuritySensorStatusNotificationEvent,
    },
    NotificationType.IRRIGATION: {
        IrrigationDeviceConfigurationStatusNotificationEvent,
        IrrigationScheduleStatusNotificationEvent,
        IrrigationValveRunStatusNotificationEvent,
    },
    NotificationType.LIGHT_SENSOR: {
        LightSensorLightDetectionStatusNotificationEvent,
    },
    NotificationType.PEST_CONTROL: {
        PestControlTrapStatusNotificationEvent,
    },
    NotificationType.POWER_MANAGEMENT: {
        PowerManagementBackupBatteryLevelStatusNotificationEvent,
        PowerManagementBatteryLevelStatusNotificationEvent,
        PowerManagementBatteryLoadStatusNotificationEvent,
        PowerManagementBatteryMaintenanceStatusNotificationEvent,
        PowerManagementLoadErrorStatusNotificationEvent,
        PowerManagementMainsStatusNotificationEvent,
        PowerManagementOverCurrentStatusNotificationEvent,
        PowerManagementOverLoadStatusNotificationEvent,
        PowerManagementOverVoltageStatusNotificationEvent,
        PowerManagementPowerStatusNotificationEvent,
    },
    NotificationType.SIREN: {
        SirenSirenStatusNotificationEvent,
    },
    NotificationType.SMOKE_ALARM: {
        SmokeAlarmAlarmStatusNotificationEvent,
        SmokeAlarmDustInDeviceStatusNotificationEvent,
        SmokeAlarmMaintenanceStatusNotificationEvent,
        SmokeAlarmPeriodicInspectionStatusNotificationEvent,
        SmokeAlarmSensorStatusNotificationEvent,
    },
    NotificationType.WATER_ALARM: {
        WaterAlarmMaintenanceStatusNotificationEvent,
        WaterAlarmPumpStatusNotificationEvent,
        WaterAlarmSensorStatusNotificationEvent,
        WaterAlarmWaterFlowAlarmStatusNotificationEvent,
        WaterAlarmWaterLevelAlarmStatusNotificationEvent,
        WaterAlarmWaterPressureAlarmStatusNotificationEvent,
        WaterAlarmWaterTemperatureAlarmStatusNotificationEvent,
    },
    NotificationType.WATER_QUALITY_MONITORING: {
        WaterQualityMonitoringAciditySensorStatusNotificationEvent,
        WaterQualityMonitoringAcidityStatusNotificationEvent,
        WaterQualityMonitoringChlorineAlarmStatusNotificationEvent,
        WaterQualityMonitoringChlorineSensorStatusNotificationEvent,
        WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent,
        WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent,
        WaterQualityMonitoringDryProtectionStatusNotificationEvent,
        WaterQualityMonitoringFilterCleaningStatusNotificationEvent,
        WaterQualityMonitoringFilterPumpStatusNotificationEvent,
        WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent,
        WaterQualityMonitoringHeatingStatusNotificationEvent,
        WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent,
        WaterQualityMonitoringWaterTankStatusNotificationEvent,
        WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent,
        WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent,
    },
    NotificationType.WATER_VALVE: {
        WaterValveMasterValveCurrentAlarmStatusNotificationEvent,
        WaterValveMasterValveOperationStatusNotificationEvent,
        WaterValveMasterValveShortCircuitStatusNotificationEvent,
        WaterValveValveCurrentAlarmStatusNotificationEvent,
        WaterValveValveOperationStatusNotificationEvent,
        WaterValveValveShortCircuitStatusNotificationEvent,
    },
    NotificationType.WEATHER_ALARM: {
        WeatherAlarmFreezeAlarmStatusNotificationEvent,
        WeatherAlarmMoistureAlarmStatusNotificationEvent,
        WeatherAlarmRainAlarmStatusNotificationEvent,
    },
}


# ----------------------------------------------------------------------------------- #
# **END OF AUTOGENERATED CONTENT** (DO NOT EDIT/REMOVE THIS COMMENT BLOCK AND DO NOT  #
# EDIT ANYTHING ABOVE IT. IF A NEW IMPORT IS NEEDED, UPDATE THE LINES AROUND 135      #
# IN scripts/generate_multilevel_sensor_constants.py THEN RE-RUN THE SCRIPT. ALL      #
# LINES WRITTEN BELOW THIS BLOCK WILL BE PRESERVED AS LONG AS THIS BLOCK REMAINS)     #
# ----------------------------------------------------------------------------------- #
