"""Constants for the Notification CC."""

# ----------------------------------------------------------------------------------- #
# **BEGINNING OF AUTOGENERATED CONTENT** (TO ADD ADDITIONAL MANUAL CONTENT, LOOK FOR  #
# THE "END OF AUTOGENERATED CONTENT" COMMENT BLOCK AND ADD YOUR CODE BELOW IT)        #
# ----------------------------------------------------------------------------------- #

from __future__ import annotations

from enum import IntEnum

CC_SPECIFIC_NOTIFICATION_TYPE = "notificationType"


class NotificationType(IntEnum):
    """Enum for known notification types for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ACCESS_CONTROL = 6
    APPLIANCE = 12
    CLOCK = 11
    CO_ALARM = 2
    CO2_ALARM = 3
    GAS_ALARM = 18
    HEAT_ALARM = 4
    HOME_HEALTH = 13
    HOME_MONITORING = 22
    HOME_SECURITY = 7
    IRRIGATION = 17
    LIGHT_SENSOR = 20
    PEST_CONTROL = 19
    POWER_MANAGEMENT = 8
    SIREN = 14
    SMOKE_ALARM = 1
    SYSTEM = 10
    WATER_ALARM = 5
    WATER_QUALITY_MONITORING = 21
    WATER_VALVE = 15
    WEATHER_ALARM = 16


class NotificationEvent(IntEnum):
    """Common base class for Notification CC states enums."""


class AccessControlLockStateNotificationEvent(NotificationEvent):
    """Enum for known access control lock state notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_JAMMED = 11
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlKeypadStateNotificationEvent(NotificationEvent):
    """Enum for known access control keypad state notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_BUSY = 17
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_TEMPORARY_DISABLED = 16
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlDoorStateNotificationEvent(NotificationEvent):
    """Enum for known access control door state notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34
    WINDOW_DOOR_IS_CLOSED = 23
    WINDOW_DOOR_IS_OPEN = 22


class AccessControlDoorHandleStateNotificationEvent(NotificationEvent):
    """Enum for known access control door handle state notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34
    WINDOW_DOOR_HANDLE_IS_CLOSED = 25
    WINDOW_DOOR_HANDLE_IS_OPEN = 24


class AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known access control barrier performing initialization process status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_PERFORMING_INITIALIZATION_PROCESS = 64
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierUlDisablingStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier ul disabling status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    BARRIER_UNATTENDED_OPERATION_HAS_BEEN_DISABLED_PER_UL_REQUIREMENTS = 69
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierVacationModeStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier vacation mode status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    BARRIER_VACATION_MODE = 71
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier safety beam obstacle status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SAFETY_BEAM_OBSTACLE = 72
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SENSOR_NOT_DETECTED_SUPERVISORY_ERROR = 73
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierBatteryStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier battery status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_SENSOR_LOW_BATTERY_WARNING = 74
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier short-circuit status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_DETECTED_SHORT_IN_WALL_STATION_WIRES = 75
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class AccessControlBarrierControlStatusNotificationEvent(NotificationEvent):
    """Enum for known access control barrier control status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALL_USER_CODES_DELETED = 12
    AUTO_LOCK_LOCKED_OPERATION = 9
    AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION = 10
    BARRIER_ASSOCIATED_WITH_NON_Z_WAVE_REMOTE_CONTROL = 76
    BARRIER_FAILED_TO_PERFORM_REQUESTED_OPERATION_DEVICE_MALFUNCTION = 70
    BARRIER_MOTOR_HAS_EXCEEDED_MANUFACTURER_S_OPERATIONAL_TIME_LIMIT = 66
    BARRIER_OPERATION_OPEN_CLOSE_FORCE_HAS_BEEN_EXCEEDED = 65
    BARRIER_OPERATION_HAS_EXCEEDED_PHYSICAL_MECHANICAL_LIMITS = 67
    BARRIER_UNABLE_TO_PERFORM_REQUESTED_OPERATION_DUE_TO_UL_REQUIREMENTS = 68
    KEYPAD_LOCK_OPERATION = 5
    KEYPAD_UNLOCK_OPERATION = 6
    LOCK_OPERATION_WITH_USER_CODE = 33
    LOCKED_BY_RF_WITH_INVALID_USER_CODE = 21
    MANUAL_LOCK_OPERATION = 1
    MANUAL_NOT_FULLY_LOCKED_OPERATION = 7
    MANUAL_UNLOCK_OPERATION = 2
    MANUALLY_ENTER_USER_ACCESS_CODE_EXCEEDS_CODE_LIMIT = 19
    MESSAGING_USER_CODE_ENTERED_VIA_KEYPAD = 32
    NEW_PROGRAM_CODE_ENTERED_UNIQUE_CODE_FOR_LOCK_CONFIGURATION = 18
    NEW_USER_CODE_ADDED = 14
    NEW_USER_CODE_NOT_ADDED_DUE_TO_DUPLICATE_CODE = 15
    RF_LOCK_OPERATION = 3
    RF_NOT_FULLY_LOCKED_OPERATION = 8
    RF_UNLOCK_OPERATION = 4
    SINGLE_USER_CODE_DELETED = 13
    UNLOCK_BY_RF_WITH_INVALID_USER_CODE = 20
    UNLOCK_OPERATION_WITH_USER_CODE = 34


class ApplianceProgramStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance program status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    PROGRAM_COMPLETED = 3
    PROGRAM_IN_PROGRESS = 2
    PROGRAM_STARTED = 1


class ApplianceMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACE_MAIN_FILTER = 4


class ApplianceApplianceStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance appliance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BOILING = 8
    DRAINING = 14
    DRYING = 18
    RINSING = 12
    SPINNING = 16
    SUPPLYING_WATER = 6
    WASHING = 10


class ApplianceTargetTemperatureFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance target temperature failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FAILURE_TO_SET_TARGET_TEMPERATURE = 5


class ApplianceWaterSupplyFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance water supply failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_SUPPLY_FAILURE = 7


class ApplianceBoilingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance boiling failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BOILING_FAILURE = 9


class ApplianceWashingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance washing failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WASHING_FAILURE = 11


class ApplianceRinsingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance rinsing failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    RINSING_FAILURE = 13


class ApplianceDrainingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance draining failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    DRAINING_FAILURE = 15


class ApplianceSpinningFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance spinning failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    SPINNING_FAILURE = 17


class ApplianceDryingFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance drying failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    DRYING_FAILURE = 19


class ApplianceFanFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance fan failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FAN_FAILURE = 20


class ApplianceCompressorFailureStatusNotificationEvent(NotificationEvent):
    """Enum for known appliance compressor failure status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    COMPRESSOR_FAILURE = 21


class CoAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CARBON_MONOXIDE_DETECTED = 2
    CARBON_MONOXIDE_DETECTED_LOCATION_PROVIDED = 1


class CoAlarmTestStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm test status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CARBON_MONOXIDE_TEST = 3


class CoAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5


class CoAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALARM_SILENCED = 6


class CoAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known co alarm periodic inspection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7


class Co2AlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CARBON_DIOXIDE_DETECTED = 2
    CARBON_DIOXIDE_DETECTED_LOCATION_PROVIDED = 1


class Co2AlarmTestStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm test status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CARBON_DIOXIDE_TEST = 3


class Co2AlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5


class Co2AlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALARM_SILENCED = 6


class Co2AlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known co2 alarm periodic inspection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7


class GasAlarmCombustibleGasStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm combustible gas status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    COMBUSTIBLE_GAS_DETECTED = 2
    COMBUSTIBLE_GAS_DETECTED_LOCATION_PROVIDED = 1


class GasAlarmToxicGasStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm toxic gas status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    TOXIC_GAS_DETECTED = 4
    TOXIC_GAS_DETECTED_LOCATION_PROVIDED = 3


class GasAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    GAS_ALARM_TEST = 5


class GasAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known gas alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACEMENT_REQUIRED = 6


class HeatAlarmHeatSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm heat sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    OVERHEAT_DETECTED = 2
    OVERHEAT_DETECTED_LOCATION_PROVIDED = 1
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3
    UNDERHEAT_DETECTED = 6
    UNDERHEAT_DETECTED_LOCATION_PROVIDED = 5


class HeatAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALARM_SILENCED = 9
    HEAT_ALARM_TEST = 7
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3


class HeatAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3
    REPLACEMENT_REQUIRED_END_OF_LIFE = 8


class HeatAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm periodic inspection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 11
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3


class HeatAlarmDustInDeviceStatusNotificationEvent(NotificationEvent):
    """Enum for known heat alarm dust in device status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_DUST_IN_DEVICE = 10
    RAPID_TEMPERATURE_FALL = 13
    RAPID_TEMPERATURE_FALL_LOCATION_PROVIDED = 12
    RAPID_TEMPERATURE_RISE = 4
    RAPID_TEMPERATURE_RISE_LOCATION_PROVIDED = 3


class HomeHealthPositionStatusNotificationEvent(NotificationEvent):
    """Enum for known home health position status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FALL_DETECTED = 12
    LEAVING_BED = 1
    LYING_ON_BED = 3
    POSTURE_CHANGED = 4
    SITTING_ON_BED = 2
    SITTING_ON_BED_EDGE = 5


class HomeHealthVocLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known home health voc level status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    VOLATILE_ORGANIC_COMPOUND_LEVEL = 6


class HomeHealthSleepApneaStatusNotificationEvent(NotificationEvent):
    """Enum for known home health sleep apnea status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    SLEEP_APNEA_DETECTED = 7


class HomeHealthSleepStageStatusNotificationEvent(NotificationEvent):
    """Enum for known home health sleep stage status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FALL_DETECTED = 12
    POSTURE_CHANGED = 4
    SLEEP_STAGE_0_DETECTED_DREAMING_REM = 8
    SLEEP_STAGE_1_DETECTED_LIGHT_SLEEP_NON_REM_1 = 9
    SLEEP_STAGE_2_DETECTED_MEDIUM_SLEEP_NON_REM_2 = 10
    SLEEP_STAGE_3_DETECTED_DEEP_SLEEP_NON_REM_3 = 11


class HomeMonitoringHomeOccupancyStatusNotificationEvent(NotificationEvent):
    """Enum for known home monitoring home occupancy status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    HOME_OCCUPIED = 2
    HOME_OCCUPIED_LOCATION_PROVIDED = 1


class HomeSecuritySensorStatusNotificationEvent(NotificationEvent):
    """Enum for known home security sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    INTRUSION = 2
    INTRUSION_LOCATION_PROVIDED = 1
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9


class HomeSecurityCoverStatusNotificationEvent(NotificationEvent):
    """Enum for known home security cover status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_COVER_REMOVED = 3
    TAMPERING_PRODUCT_MOVED = 9


class HomeSecurityMotionSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known home security motion sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    MOTION_DETECTION = 8
    MOTION_DETECTION_LOCATION_PROVIDED = 7
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9


class HomeSecurityMagneticInterferenceStatusNotificationEvent(NotificationEvent):
    """Enum for known home security magnetic interference status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    GLASS_BREAKAGE = 6
    GLASS_BREAKAGE_LOCATION_PROVIDED = 5
    IMPACT_DETECTED = 10
    MAGNETIC_FIELD_INTERFERENCE_DETECTED = 11
    RF_JAMMING_DETECTED = 12
    TAMPERING_INVALID_CODE = 4
    TAMPERING_PRODUCT_MOVED = 9


class IrrigationScheduleStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation schedule (id) status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    SCHEDULE_FINISHED = 2
    SCHEDULE_STARTED = 1


class IrrigationValveRunStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation valve (id) run status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    VALVE_TABLE_RUN_FINISHED = 4
    VALVE_TABLE_RUN_STARTED = 3


class IrrigationDeviceConfigurationStatusNotificationEvent(NotificationEvent):
    """Enum for known irrigation device configuration status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    DEVICE_IS_NOT_CONFIGURED = 5


class LightSensorLightDetectionStatusNotificationEvent(NotificationEvent):
    """Enum for known light sensor light detection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    LIGHT_COLOR_TRANSITION_DETECTED = 2
    LIGHT_DETECTED = 1


class PestControlTrapStatusNotificationEvent(NotificationEvent):
    """Enum for known pest control trap status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    PEST_DETECTED = 6
    PEST_DETECTED_LOCATION_PROVIDED = 5
    PEST_EXTERMINATED = 8
    PEST_EXTERMINATED_LOCATION_PROVIDED = 7
    TRAP_ARMED = 2
    TRAP_ARMED_LOCATION_PROVIDED = 1
    TRAP_RE_ARM_REQUIRED = 4
    TRAP_RE_ARM_REQUIRED_LOCATION_PROVIDED = 3


class PowerManagementPowerStatusNotificationEvent(NotificationEvent):
    """Enum for known power management power status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    POWER_HAS_BEEN_APPLIED = 1
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementMainsStatusNotificationEvent(NotificationEvent):
    """Enum for known power management mains status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    AC_MAINS_DISCONNECTED = 2
    AC_MAINS_RE_CONNECTED = 3
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementOverCurrentStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-current status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    OVER_CURRENT_DETECTED = 6
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementOverVoltageStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-voltage status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    OVER_VOLTAGE_DETECTED = 7
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementOverLoadStatusNotificationEvent(NotificationEvent):
    """Enum for known power management over-load status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    OVER_LOAD_DETECTED = 8
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementLoadErrorStatusNotificationEvent(NotificationEvent):
    """Enum for known power management load error status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    LOAD_ERROR = 9
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementBatteryMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BATTERY_FLUID_IS_LOW = 17
    REPLACE_BATTERY_NOW = 11
    REPLACE_BATTERY_SOON = 10
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementBatteryLoadStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery load status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BATTERY_IS_CHARGING = 12
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementBatteryLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known power management battery level status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BATTERY_IS_FULLY_CHARGED = 13
    CHARGE_BATTERY_NOW = 15
    CHARGE_BATTERY_SOON = 14
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class PowerManagementBackupBatteryLevelStatusNotificationEvent(NotificationEvent):
    """Enum for known power management backup battery level status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    BACK_UP_BATTERY_DISCONNECTED = 18
    BACK_UP_BATTERY_IS_LOW = 16
    SURGE_DETECTED = 4
    VOLTAGE_DROP_DRIFT = 5


class SirenSirenStatusNotificationEvent(NotificationEvent):
    """Enum for known siren siren status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    SIREN_ACTIVE = 1


class SmokeAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    SMOKE_DETECTED = 2
    SMOKE_DETECTED_LOCATION_PROVIDED = 1


class SmokeAlarmAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ALARM_SILENCED = 6
    SMOKE_ALARM_TEST = 3


class SmokeAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACEMENT_REQUIRED = 4
    REPLACEMENT_REQUIRED_END_OF_LIFE = 5


class SmokeAlarmPeriodicInspectionStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm periodic inspection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_PLANNED_PERIODIC_INSPECTION = 7


class SmokeAlarmDustInDeviceStatusNotificationEvent(NotificationEvent):
    """Enum for known smoke alarm dust in device status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MAINTENANCE_REQUIRED_DUST_IN_DEVICE = 8


class WaterAlarmSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_LEAK_DETECTED = 2
    WATER_LEAK_DETECTED_LOCATION_PROVIDED = 1
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3


class WaterAlarmMaintenanceStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm maintenance status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    REPLACE_WATER_FILTER = 5
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3


class WaterAlarmWaterFlowAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water flow alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_FLOW_ALARM = 6
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3


class WaterAlarmWaterPressureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water pressure alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3
    WATER_PRESSURE_ALARM = 7


class WaterAlarmWaterTemperatureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water temperature alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3
    WATER_TEMPERATURE_ALARM = 8


class WaterAlarmWaterLevelAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm water level alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_LEVEL_ALARM = 9
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3


class WaterAlarmPumpStatusNotificationEvent(NotificationEvent):
    """Enum for known water alarm pump status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    SUMP_PUMP_ACTIVE = 10
    SUMP_PUMP_FAILURE = 11
    WATER_LEVEL_DROPPED = 4
    WATER_LEVEL_DROPPED_LOCATION_PROVIDED = 3


class WaterQualityMonitoringChlorineAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring chlorine alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CHLORINE_ALARM = 1


class WaterQualityMonitoringAcidityStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring acidity (ph) status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ACIDITY_PH_ALARM = 2


class WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring water oxidation alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_OXIDATION_ALARM = 3


class WaterQualityMonitoringChlorineSensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring chlorine sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    CHLORINE_EMPTY = 4


class WaterQualityMonitoringAciditySensorStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring acidity (ph) sensor status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    ACIDITY_PH_EMPTY = 5


class WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring waterflow measuring station sensor notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATERFLOW_MEASURING_STATION_SHORTAGE_DETECTED = 6


class WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring waterflow clear water sensor notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATERFLOW_CLEAR_WATER_SHORTAGE_DETECTED = 7


class WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring disinfection system status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    DISINFECTION_SYSTEM_ERROR_DETECTED = 8


class WaterQualityMonitoringFilterCleaningStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring filter cleaning status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FILTER_CLEANING_ONGOING = 9


class WaterQualityMonitoringHeatingStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring heating status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    HEATING_OPERATION_ONGOING = 10


class WaterQualityMonitoringFilterPumpStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring filter pump status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FILTER_PUMP_OPERATION_ONGOING = 11


class WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring freshwater flow status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FRESHWATER_OPERATION_ONGOING = 12


class WaterQualityMonitoringDryProtectionStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring dry protection status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    DRY_PROTECTION_OPERATION_ACTIVE = 13


class WaterQualityMonitoringWaterTankStatusNotificationEvent(NotificationEvent):
    """Enum for known water quality monitoring water tank status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    WATER_TANK_IS_EMPTY = 14
    WATER_TANK_IS_FULL = 16
    WATER_TANK_LEVEL_IS_UNKNOWN = 15


class WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent(
    NotificationEvent
):
    """Enum for known water quality monitoring collective disorder status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    COLLECTIVE_DISORDER = 17


class WaterValveValveOperationStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve operation status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    VALVE_OPERATION = 1


class WaterValveMasterValveOperationStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve operation status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MASTER_VALVE_OPERATION = 2


class WaterValveValveShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve short circuit status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    VALVE_SHORT_CIRCUIT = 3


class WaterValveMasterValveShortCircuitStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve short circuit status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MASTER_VALVE_SHORT_CIRCUIT = 4


class WaterValveValveCurrentAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve valve current alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    VALVE_CURRENT_ALARM = 5


class WaterValveMasterValveCurrentAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known water valve master valve current alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MASTER_VALVE_CURRENT_ALARM = 6


class WeatherAlarmRainAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm rain alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    RAIN_ALARM = 1


class WeatherAlarmMoistureAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm moisture alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    MOISTURE_ALARM = 2


class WeatherAlarmFreezeAlarmStatusNotificationEvent(NotificationEvent):
    """Enum for known weather alarm freeze alarm status notification event for Notification CC."""

    # https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json
    FREEZE_ALARM = 3


NOTIFICATION_TYPE_TO_EVENT_MAP: dict[NotificationType, type[NotificationEvent]] = {
    NotificationType.ACCESS_CONTROL: {
        AccessControlBarrierBatteryStatusNotificationEvent,
        AccessControlBarrierControlStatusNotificationEvent,
        AccessControlBarrierPerformingInitializationProcessStatusNotificationEvent,
        AccessControlBarrierSafetyBeamObstacleStatusNotificationEvent,
        AccessControlBarrierSensorStatusNotificationEvent,
        AccessControlBarrierShortCircuitStatusNotificationEvent,
        AccessControlBarrierUlDisablingStatusNotificationEvent,
        AccessControlBarrierVacationModeStatusNotificationEvent,
        AccessControlDoorHandleStateNotificationEvent,
        AccessControlDoorStateNotificationEvent,
        AccessControlKeypadStateNotificationEvent,
        AccessControlLockStateNotificationEvent,
    },
    NotificationType.APPLIANCE: {
        ApplianceApplianceStatusNotificationEvent,
        ApplianceBoilingFailureStatusNotificationEvent,
        ApplianceCompressorFailureStatusNotificationEvent,
        ApplianceDrainingFailureStatusNotificationEvent,
        ApplianceDryingFailureStatusNotificationEvent,
        ApplianceFanFailureStatusNotificationEvent,
        ApplianceMaintenanceStatusNotificationEvent,
        ApplianceProgramStatusNotificationEvent,
        ApplianceRinsingFailureStatusNotificationEvent,
        ApplianceSpinningFailureStatusNotificationEvent,
        ApplianceTargetTemperatureFailureStatusNotificationEvent,
        ApplianceWashingFailureStatusNotificationEvent,
        ApplianceWaterSupplyFailureStatusNotificationEvent,
    },
    NotificationType.CO_ALARM: {
        CoAlarmAlarmStatusNotificationEvent,
        CoAlarmMaintenanceStatusNotificationEvent,
        CoAlarmPeriodicInspectionStatusNotificationEvent,
        CoAlarmSensorStatusNotificationEvent,
        CoAlarmTestStatusNotificationEvent,
    },
    NotificationType.CO2_ALARM: {
        Co2AlarmAlarmStatusNotificationEvent,
        Co2AlarmMaintenanceStatusNotificationEvent,
        Co2AlarmPeriodicInspectionStatusNotificationEvent,
        Co2AlarmSensorStatusNotificationEvent,
        Co2AlarmTestStatusNotificationEvent,
    },
    NotificationType.GAS_ALARM: {
        GasAlarmAlarmStatusNotificationEvent,
        GasAlarmCombustibleGasStatusNotificationEvent,
        GasAlarmMaintenanceStatusNotificationEvent,
        GasAlarmToxicGasStatusNotificationEvent,
    },
    NotificationType.HEAT_ALARM: {
        HeatAlarmAlarmStatusNotificationEvent,
        HeatAlarmDustInDeviceStatusNotificationEvent,
        HeatAlarmHeatSensorStatusNotificationEvent,
        HeatAlarmMaintenanceStatusNotificationEvent,
        HeatAlarmPeriodicInspectionStatusNotificationEvent,
    },
    NotificationType.HOME_HEALTH: {
        HomeHealthPositionStatusNotificationEvent,
        HomeHealthSleepApneaStatusNotificationEvent,
        HomeHealthSleepStageStatusNotificationEvent,
        HomeHealthVocLevelStatusNotificationEvent,
    },
    NotificationType.HOME_MONITORING: {
        HomeMonitoringHomeOccupancyStatusNotificationEvent,
    },
    NotificationType.HOME_SECURITY: {
        HomeSecurityCoverStatusNotificationEvent,
        HomeSecurityMagneticInterferenceStatusNotificationEvent,
        HomeSecurityMotionSensorStatusNotificationEvent,
        HomeSecuritySensorStatusNotificationEvent,
    },
    NotificationType.IRRIGATION: {
        IrrigationDeviceConfigurationStatusNotificationEvent,
        IrrigationScheduleStatusNotificationEvent,
        IrrigationValveRunStatusNotificationEvent,
    },
    NotificationType.LIGHT_SENSOR: {
        LightSensorLightDetectionStatusNotificationEvent,
    },
    NotificationType.PEST_CONTROL: {
        PestControlTrapStatusNotificationEvent,
    },
    NotificationType.POWER_MANAGEMENT: {
        PowerManagementBackupBatteryLevelStatusNotificationEvent,
        PowerManagementBatteryLevelStatusNotificationEvent,
        PowerManagementBatteryLoadStatusNotificationEvent,
        PowerManagementBatteryMaintenanceStatusNotificationEvent,
        PowerManagementLoadErrorStatusNotificationEvent,
        PowerManagementMainsStatusNotificationEvent,
        PowerManagementOverCurrentStatusNotificationEvent,
        PowerManagementOverLoadStatusNotificationEvent,
        PowerManagementOverVoltageStatusNotificationEvent,
        PowerManagementPowerStatusNotificationEvent,
    },
    NotificationType.SIREN: {
        SirenSirenStatusNotificationEvent,
    },
    NotificationType.SMOKE_ALARM: {
        SmokeAlarmAlarmStatusNotificationEvent,
        SmokeAlarmDustInDeviceStatusNotificationEvent,
        SmokeAlarmMaintenanceStatusNotificationEvent,
        SmokeAlarmPeriodicInspectionStatusNotificationEvent,
        SmokeAlarmSensorStatusNotificationEvent,
    },
    NotificationType.WATER_ALARM: {
        WaterAlarmMaintenanceStatusNotificationEvent,
        WaterAlarmPumpStatusNotificationEvent,
        WaterAlarmSensorStatusNotificationEvent,
        WaterAlarmWaterFlowAlarmStatusNotificationEvent,
        WaterAlarmWaterLevelAlarmStatusNotificationEvent,
        WaterAlarmWaterPressureAlarmStatusNotificationEvent,
        WaterAlarmWaterTemperatureAlarmStatusNotificationEvent,
    },
    NotificationType.WATER_QUALITY_MONITORING: {
        WaterQualityMonitoringAciditySensorStatusNotificationEvent,
        WaterQualityMonitoringAcidityStatusNotificationEvent,
        WaterQualityMonitoringChlorineAlarmStatusNotificationEvent,
        WaterQualityMonitoringChlorineSensorStatusNotificationEvent,
        WaterQualityMonitoringCollectiveDisorderStatusNotificationEvent,
        WaterQualityMonitoringDisinfectionSystemStatusNotificationEvent,
        WaterQualityMonitoringDryProtectionStatusNotificationEvent,
        WaterQualityMonitoringFilterCleaningStatusNotificationEvent,
        WaterQualityMonitoringFilterPumpStatusNotificationEvent,
        WaterQualityMonitoringFreshwaterFlowStatusNotificationEvent,
        WaterQualityMonitoringHeatingStatusNotificationEvent,
        WaterQualityMonitoringWaterOxidationAlarmStatusNotificationEvent,
        WaterQualityMonitoringWaterTankStatusNotificationEvent,
        WaterQualityMonitoringWaterflowClearWaterSensorNotificationEvent,
        WaterQualityMonitoringWaterflowMeasuringStationSensorNotificationEvent,
    },
    NotificationType.WATER_VALVE: {
        WaterValveMasterValveCurrentAlarmStatusNotificationEvent,
        WaterValveMasterValveOperationStatusNotificationEvent,
        WaterValveMasterValveShortCircuitStatusNotificationEvent,
        WaterValveValveCurrentAlarmStatusNotificationEvent,
        WaterValveValveOperationStatusNotificationEvent,
        WaterValveValveShortCircuitStatusNotificationEvent,
    },
    NotificationType.WEATHER_ALARM: {
        WeatherAlarmFreezeAlarmStatusNotificationEvent,
        WeatherAlarmMoistureAlarmStatusNotificationEvent,
        WeatherAlarmRainAlarmStatusNotificationEvent,
    },
}


# ----------------------------------------------------------------------------------- #
# **END OF AUTOGENERATED CONTENT** (DO NOT EDIT/REMOVE THIS COMMENT BLOCK AND DO NOT  #
# EDIT ANYTHING ABOVE IT. IF A NEW IMPORT IS NEEDED, UPDATE THE LINES AROUND 135      #
# IN scripts/generate_multilevel_sensor_constants.py THEN RE-RUN THE SCRIPT. ALL      #
# LINES WRITTEN BELOW THIS BLOCK WILL BE PRESERVED AS LONG AS THIS BLOCK REMAINS)     #
# ----------------------------------------------------------------------------------- #
