#!/usr/bin/env python3
"""Script to generate Notification CC constants."""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
from collections import defaultdict
from collections.abc import Callable, Mapping

import requests
from slugify import slugify

GITHUB_PROJECT = "zwave-js/node-zwave-js"
BRANCH_NAME = "master"
NOTIFICATIONS_FILE_PATH = "packages/config/config/notifications.json"

CONST_FILE_PATH = pathlib.Path(__file__).parent.joinpath(
    "../zwave_js_server/const/command_class/notification.py"
)


def remove_comments(text: str) -> str:
    """Remove comments from a JSON string."""
    return "\n".join(
        line for line in text.split("\n") if not line.strip().startswith("//")
    )


def remove_parenthesis(text: str) -> str:
    """Remove text in parenthesis from a string."""
    return re.sub(r"\([^)]*\)", "", text)


def enum_name_format(name: str, should_remove_parenthesis: bool) -> str:
    """Convert sensor/scale name to enum format."""
    if should_remove_parenthesis:
        name = remove_parenthesis(name)
    return slugify(name, separator="_").upper()


def normalize_name(name: str) -> str:
    """Convert a sensor/scale name into a normalized name."""
    return enum_name_format(name, True).replace("_", " ").title()


def format_for_class_name(name: str) -> str:
    """Convert sensor/scale name to class name format."""
    return normalize_name(name).replace(" ", "")


notifications_file = json.loads(
    remove_comments(
        requests.get(
            (
                f"https://raw.githubusercontent.com/{GITHUB_PROJECT}/{BRANCH_NAME}/"
                f"{NOTIFICATIONS_FILE_PATH}"
            ),
            timeout=10,
        ).text
    )
)

notifications = {}
for notification_type, notification_payload in notifications_file.items():
    notification_type = int(notification_type, 16)
    notification_name = notification_payload["name"].title()
    notifications[notification_name] = {
        "type": notification_type,
        "variables": {},
        "events": {},
    }
    for variable in notification_payload.get("variables", []):
        variable_name = variable["name"].title()
        states = notifications[notification_name]["variables"].setdefault(
            variable_name, {}
        )
        for state_id, state_props in variable["states"].items():
            state_id = int(state_id, 16)
            state_name = state_props["label"].title()
            states[state_name] = state_id
    for event_id, event_data in notification_payload.get("events", {}).items():
        event_id = int(event_id, 16)
        notifications[notification_name]["events"][
            event_data["label"].title()
        ] = event_id


notifications = dict(sorted(notifications.items(), key=lambda kv: kv[0]))


def generate_int_enum_class_definition(
    class_name: str,
    enum_map: Mapping[str, int | str | dict],
    enum_ref_url: str | None = None,
    get_id_func: Callable | None = None,
    docstring_info: str = "",
    base_class: str = "IntEnum",
) -> list[str]:
    """Generate an IntEnum class definition as an array of lines of string."""
    class_def: list[str] = []
    class_def.append(f"class {class_name}({base_class}):")
    docstring = f'"""Enum for known {docstring_info} for Notification CC."""'.replace(
        "  ", " "
    )
    class_def.append(f"    {docstring}")
    if enum_ref_url:
        class_def.append(f"    # {enum_ref_url}")
    for enum_name, enum_id in sorted(enum_map.items(), key=lambda x: x[0]):
        if get_id_func:
            enum_id = get_id_func(enum_id)
        class_def.append(f"    {enum_name_format(enum_name, False)} = {enum_id}")
    return class_def


def generate_int_enum_base_class(class_name: str, docstring: str) -> list[str]:
    """Generate an IntEnum base class definition."""
    class_def: list[str] = []
    class_def.append(f"class {class_name}(IntEnum):")
    class_def.append(f"\t{docstring}")
    return class_def


NOTIFICATIONS_URL = (
    f"https://github.com/{GITHUB_PROJECT}/blob/{BRANCH_NAME}/{NOTIFICATIONS_FILE_PATH}"
)

lines = [
    '"""Constants for the Notification CC."""',
    "",
    "# ----------------------------------------------------------------------------------- #",
    "# **BEGINNING OF AUTOGENERATED CONTENT** (TO ADD ADDITIONAL MANUAL CONTENT, LOOK FOR  #",
    '# THE "END OF AUTOGENERATED CONTENT" COMMENT BLOCK AND ADD YOUR CODE BELOW IT)        #',
    "# ----------------------------------------------------------------------------------- #",
    "",
    "from __future__ import annotations",
    "",
    "from enum import IntEnum",
    'CC_SPECIFIC_NOTIFICATION_TYPE = "notificationType"',
]

lines.extend(
    generate_int_enum_class_definition(
        "NotificationType",
        notifications,
        NOTIFICATIONS_URL,
        get_id_func=lambda x: x["type"],
        docstring_info="notification types",
    )
)

lines.extend(
    generate_int_enum_base_class(
        "NotificationEvent",
        docstring='"""Common base class for Notification CC states enums."""',
    )
)

_notification_type_to_enum_map = defaultdict(list)
for notification_type, state_variable_map in notifications.items():
    for state_variable_name, state_variable_dict in state_variable_map[
        "variables"
    ].items():
        name = f"{notification_type} {state_variable_name} Notification Event"
        lines.extend(
            generate_int_enum_class_definition(
                format_for_class_name(name),
                {**state_variable_dict, **state_variable_map["events"]},
                NOTIFICATIONS_URL,
                docstring_info=name.lower(),
                base_class="NotificationEvent",
            )
        )
        _notification_type_to_enum_map[notification_type].append(
            format_for_class_name(name)
        )
notification_type_to_enum_map = dict(
    sorted(_notification_type_to_enum_map.items(), key=lambda kv: kv[0])
)
for unit_name, enum_list in notification_type_to_enum_map.items():
    notification_type_to_enum_map[unit_name] = sorted(enum_list)


notification_type_to_event_map_line = (
    "NOTIFICATION_TYPE_TO_EVENT_MAP: dict[NotificationType, "
    "type[NotificationEvent]] = {"
)
for notification_type, notification_events in notification_type_to_enum_map.items():
    notification_type_to_event_map_line += (
        f"    NotificationType.{enum_name_format(notification_type, False)}: {{"
    )
    for notification_event in notification_events:
        notification_type_to_event_map_line += f"{notification_event},"
    notification_type_to_event_map_line += "},"
notification_type_to_event_map_line += "}"
lines.append(notification_type_to_event_map_line)
lines.append("")

lines.extend(
    [
        "",
        "# ----------------------------------------------------------------------------------- #",
        "# **END OF AUTOGENERATED CONTENT** (DO NOT EDIT/REMOVE THIS COMMENT BLOCK AND DO NOT  #",
        "# EDIT ANYTHING ABOVE IT. IF A NEW IMPORT IS NEEDED, UPDATE THE LINES AROUND 135      #",
        "# IN scripts/generate_multilevel_sensor_constants.py THEN RE-RUN THE SCRIPT. ALL      #",
        "# LINES WRITTEN BELOW THIS BLOCK WILL BE PRESERVED AS LONG AS THIS BLOCK REMAINS)     #",
        "# ----------------------------------------------------------------------------------- #",
        "",
    ]
)

existing_const_file = CONST_FILE_PATH.read_text(encoding="utf-8").splitlines()

manually_written_code_start_idx = (
    next(
        i
        for i, line in enumerate(existing_const_file)
        if "**END OF AUTOGENERATED CONTENT**" in line
    )
    + 6
)
if len(existing_const_file) > manually_written_code_start_idx:
    lines.extend(
        [
            line.strip("\n")
            for line in existing_const_file[manually_written_code_start_idx:]
        ]
    )

CONST_FILE_PATH.write_text("\n".join(lines), encoding="utf-8")

if subprocess.run(["which", "black"], capture_output=True, check=True).stdout:
    subprocess.run(
        ["black", CONST_FILE_PATH],
        check=True,
    )
else:
    print("Could not run black on new file, please run it to properly format it.")
